[nixpacks]
provider = "python"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "lua5.4"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "python main.py"
