[nixpacks]
provider = "python"

[phases.setup]
nixPkgs = ["python311", "lua5.4", "gcc", "make"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python main.py"
